# Generated by Django 4.1 on 2022-08-14 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ref", models.CharField(max_length=50, verbose_name="Ref")),
            ],
        ),
        migrations.CreateModel(
            name="RoomReservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reservation_ref",
                    models.CharField(max_length=50, verbose_name="Reservation Ref"),
                ),
                ("checkin_date", models.DateField(verbose_name="Checkin date")),
                ("checkout_date", models.DateField(verbose_name="Checkout date")),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="rental.room"
                    ),
                ),
            ],
        ),
    ]
